version: "3.7"

services:
  mysql:
    image: mysql:5.6
    container_name: tars-mysql
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - /home/kk/learn_tars/data/mysql:/var/lib/mysql:rw
      - /etc/localtime:/etc/localtime
    networks:
      internal:
        ipv4_address: 172.25.1.2

  framework:
    image: dik/tars-framework:v0
    container_name: tars-framework
    ports:
      - "3000:3000"
    restart: always
    networks:
      internal:
        ipv4_address: 172.25.1.3
    environment:
      MYSQL_HOST: "172.25.1.2"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "root"
      MYSQL_PORT: 3306
      REBUILD: "false"
      INET: eth0
      SLAVE: "false"
    volumes:
      - /home/kk/learn_tars/data/framework:/data/tars:rw
      - /etc/localtime:/etc/localtime
    depends_on:
      - mysql
  node:
    image: dik/tarscpp-node:v0
    container_name: tars-node
    restart: always
    networks:
      internal:
        ipv4_address: 172.25.1.5
    volumes:
      - /home/kk/learn_tars/data/node:/data/tars:rw
      - /home/kk/learn_tars/app:/root/app:rw
      - /etc/localtime:/etc/localtime
    environment:
      INET: eth0
      WEB_HOST: "http://172.25.1.3:3000"
    ports:
      - "9000-9010:9000-9010"
    depends_on:
      - framework

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.1.0/16
