FROM ubuntu:14.04


RUN apt-get update && \
    #apt-get install -y build-essential && \
    apt-get install -y gcc-4.9.2 && \
    apt-get install -y g++-4.9.2 && \
    # clean
    apt-get clean && apt-get autoclean && apt-get autoremove && \
    rm -rf /tmp/* && \
    echo 'finish'